
resdata man
        db '<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">'
        db '<assemblyIdentity '
        db 'version="1.0.0.0" '
        db 'processorArchitecture="amd64" '
        db 'name="addpath" '
        db 'type="win64"/>'
        db '<trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">'
        db '<security>'
        db '<requestedPrivileges>'
        db '<requestedExecutionLevel '
        db 'level="requireAdministrator" '
        db 'uiAccess="false"/>'
        db '</requestedPrivileges>'
        db '</security>'
        db '</trustInfo>'
        db '</assembly>'
endres